### ISSUE TITLE
Reviewer Comments To ADdress

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#134]
- [ ] SPAAM-community/AMDirT#135
- [ ] (Major) Add library column filtering to viewer (see SPAAM-community/AMDirT#126 for front end)
- [ ] SPAAM-community/AncientMetagenomeDir#1131
- [ ] SPAAM-community/AMDirT#137
- [ ] SPAAM-community/AMDirT#138
- [ ] SPAAM-community/AMDirT#139
